import { writeFileSync } from "node:fs";
import { ensureDir, type ResolvedPaths } from "./config.js";
import { TEMPLATES } from "./templates.js";
import type { AimemoryConfig, IndexData } from "../types.js";

/** Escape a label for use inside a mermaid mindmap node. */
function safeLabel(text: string): string {
  return text
    .replace(/[\r\n]+/g, " ")
    .replace(/["`]/g, "'")
    .replace(/[()]/g, "")
    .replace(/[[\]{}]/g, "")
    .trim();
}

/**
 * Build a deterministic mermaid `mindmap` from the index: root -> one node per
 * governance file (with its one-line summary) -> child nodes per H2 heading.
 * No LLM involved; purely structural, so it is cheap and reproducible.
 */
export function buildMindmap(config: AimemoryConfig, index: IndexData): string {
  const lines: string[] = ["mindmap", "  root((Project))"];
  for (const key of config.files) {
    const entry = index.files[key];
    const tpl = TEMPLATES[key];
    const title = tpl?.title ?? key;
    const status = entry.exists ? "" : " [missing]";
    lines.push(`    ${safeLabel(title)}${status}`);
    if (entry.summary) {
      lines.push(`      ::icon(fa fa-info)`);
      lines.push(`      ${safeLabel(entry.summary)}`);
    }
    for (const heading of entry.headings) {
      lines.push(`      ${safeLabel(heading)}`);
    }
  }
  return lines.join("\n");
}

/** Render the full mindmap.md document (fenced mermaid + text summary table). */
export function renderMindmapDoc(config: AimemoryConfig, index: IndexData): string {
  const mermaid = buildMindmap(config, index);
  const rows = config.files.map((key) => {
    const e = index.files[key];
    const tpl = TEMPLATES[key];
    const state = e.exists ? "ok" : "missing";
    const summary = e.summary || (tpl ? tpl.purpose : "");
    return `| ${key} | ${state} | ${summary.replace(/\|/g, "\\|")} |`;
  });
  return [
    "# Project Mind Map",
    "",
    "<!-- Auto-generated by aimemory. Do not edit by hand. -->",
    "",
    "```mermaid",
    mermaid,
    "```",
    "",
    "## Index",
    "",
    "| File | State | Summary |",
    "| --- | --- | --- |",
    ...rows,
    "",
    `_Updated: ${new Date().toISOString()}_`,
    "",
  ].join("\n");
}

export function writeMindmap(
  p: ResolvedPaths,
  config: AimemoryConfig,
  index: IndexData,
): string {
  ensureDir(p.systemDir);
  const doc = renderMindmapDoc(config, index);
  writeFileSync(p.mindmapPath, doc, "utf8");
  return doc;
}
